# Form implementation generated from reading ui file 'addBook.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(QtWidgets.QWidget):
    def __init__(self, cursor):
        super(Ui_Form, self).__init__()
        self.cursor = cursor
        self.img = None
        self.imgtype = ""
        self.setupUi(self)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 500)
        self.formLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 90, 301, 311))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(10, 10, 10, 10)
        self.formLayout.setHorizontalSpacing(10)
        self.formLayout.setVerticalSpacing(30)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.addBid = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.addBid.setObjectName("addBid")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.addBid)
        self.label_2 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.addBname = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.addBname.setObjectName("addBname")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.addBname)
        self.label_3 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.addAuthor = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.addAuthor.setObjectName("addAuthor")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.addAuthor)
        self.label_4 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.addPublisher = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.addPublisher.setObjectName("addPublisher")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.addPublisher)
        self.label_5 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.comboBox = QtWidgets.QComboBox(parent=self.formLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboBox)
        self.label_6 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_6)
        self.chooseImg = QtWidgets.QPushButton(parent=self.formLayoutWidget)
        self.chooseImg.setObjectName("chooseImg")

        # 选择图片按钮绑定事件
        self.chooseImg.clicked.connect(self.uploadImg)

        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.chooseImg)
        self.cover = QtWidgets.QGraphicsView(parent=Form)
        self.cover.setGeometry(QtCore.QRect(340, 100, 231, 191))
        self.cover.setObjectName("cover")
        self.addSure = QtWidgets.QPushButton(parent=Form)
        self.addSure.setGeometry(QtCore.QRect(470, 400, 101, 31))
        self.addSure.setObjectName("addSure")

        # 确认添加按钮绑定事件
        self.addSure.clicked.connect(self.add)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "添加图书"))
        self.label.setText(_translate("Form", "编   号："))
        self.label_2.setText(_translate("Form", "书   名："))
        self.label_3.setText(_translate("Form", "作   者："))
        self.label_4.setText(_translate("Form", "出版社："))
        self.label_5.setText(_translate("Form", "状   态："))
        self.comboBox.setItemText(0, _translate("Form", "在馆"))
        self.comboBox.setItemText(1, _translate("Form", "已预约"))
        self.comboBox.setItemText(2, _translate("Form", "已借出"))
        self.label_6.setText(_translate("Form", "封   面："))
        self.chooseImg.setText(_translate("Form", "选择本地图片"))
        self.addSure.setText(_translate("Form", "确认添加"))

    # 图片操作
    def uploadImg(self):
        imgName, imgType = QtWidgets.QFileDialog.getOpenFileName(self, "选择图片", "", "Image Files(*.jpg *.png)")
        # print(imgName)
        # 根据路径获得图片
        img = QtGui.QPixmap(imgName).scaled(self.cover.width() - 10, self.cover.height() - 10)
        # 用 QGraphicsView 显示图片
        scene = QtWidgets.QGraphicsScene()
        scene.addPixmap(img)
        self.cover.setScene(scene)
        self.img = img
        self.imgtype = imgName.split(".")[-1]

    # 添加图书
    def add(self):
        bid = self.addBid.text()
        bname = self.addBname.text()
        author = self.addAuthor.text()
        publisher = self.addPublisher.text()
        status = self.comboBox.currentText()
        if bid == "" or bname == "" or author == "" or publisher == "":
            QtWidgets.QMessageBox.warning(self, "警告", "请填写完整信息！")
        if status == "在馆":
            status = 0
        elif status == "已预约":
            status = 1
        else:
            status = 2

        # 保存图片到 img 目录下
        imgName = bid + "." + self.imgtype
        self.img.save("img/" + imgName)

        # print(bid, bname, author, publisher, status)
        sql = "insert into book(bid, cover, bname, author, publisher, status) values(%s, %s, %s, %s, %s, %s)"
        try:
            self.cursor.execute(sql, (bid, imgName, bname, author, publisher, status))
            self.cursor.connection.commit()
            QtWidgets.QMessageBox.information(self, "提示", "添加成功！")
        except Exception as e:
            if "Duplicate" in str(e):
                QtWidgets.QMessageBox.warning(self, "警告", "编号重复！")
            else:
                QtWidgets.QMessageBox.warning(self, "警告", "添加失败！")


if __name__ == "__main__":
    import sys
    import pymysql
    app = QtWidgets.QApplication(sys.argv)
    db = pymysql.connect(
        host="localhost",
        user="root",
        password="10086",
        database="library",
        charset="utf8"
    )
    cursor = db.cursor()
    ui = Ui_Form(cursor)
    ui.show()
    sys.exit(app.exec())
