# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_Form(QtWidgets.QWidget):
    def __init__(self, cursor):
        super(Ui_Form, self).__init__()
        self.cursor = cursor
        self.setupUi(self)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(580, 511)
        self.formLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(120, 190, 331, 111))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_2.setContentsMargins(10, 10, 10, 10)
        self.formLayout_2.setHorizontalSpacing(25)
        self.formLayout_2.setVerticalSpacing(40)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.passwordInput = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordInput.setObjectName("passwordInput")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.passwordInput)
        self.usernameInput = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.usernameInput.setObjectName("usernameInput")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.usernameInput)
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(130, 320, 48, 19))
        self.label_3.setObjectName("label_3")
        self.isStudent = QtWidgets.QRadioButton(parent=Form)
        self.isStudent.setGeometry(QtCore.QRect(200, 320, 101, 19))
        self.isStudent.setObjectName("isStudent")
        self.isManager = QtWidgets.QRadioButton(parent=Form)
        self.isManager.setGeometry(QtCore.QRect(350, 320, 95, 19))
        self.isManager.setObjectName("isManager")
        self.LoginBtn = QtWidgets.QPushButton(parent=Form)
        self.LoginBtn.setGeometry(QtCore.QRect(240, 370, 91, 31))
        self.LoginBtn.setObjectName("LoginBtn")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(140, 80, 311, 81))
        self.label_4.setStyleSheet("font: 24pt \"华文行楷\";")
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        # 登录按钮绑定事件
        self.LoginBtn.clicked.connect(self.login)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "登录"))
        self.label.setText(_translate("Form", "用户名："))
        self.label_2.setText(_translate("Form", "密   码："))
        self.label_3.setText(_translate("Form", "身   份："))
        self.isStudent.setText(_translate("Form", "学生"))
        self.isManager.setText(_translate("Form", "管理员"))
        self.LoginBtn.setText(_translate("Form", "登录"))
        self.label_4.setText(_translate("Form", "图书馆信息管理系统"))

    def login(self):
        username = self.usernameInput.text()
        password = self.passwordInput.text()
        role = 0 if self.isStudent.isChecked() else 1
        # print(username, password, role)
        # 连接数据库验证
        if username == "" or password == "":
            QtWidgets.QMessageBox.warning(None, "错误", "用户名或密码不能为空")
        elif role == 1 and not self.isManager.isChecked():
            QtWidgets.QMessageBox.warning(None, "错误", "请选择身份")
        else:
            sql = "select * from user where username = %s and password = %s and role = %s"
            cursor = self.cursor
            cursor.execute(sql, (username, password, role))
            result = cursor.fetchone()
            if result:
                # QtWidgets.QMessageBox.information(None, "成功", "登录成功")
                # 如果是管理员，跳转到管理员页面，隐藏登录页面
                if role == 1:
                    from AdminPage import Ui_MainWindow
                    self.adminPage = Ui_MainWindow(cursor, username)
                    self.adminPage.show()
                    self.close()
                else:
                    print("学生")
            else:
                QtWidgets.QMessageBox.warning(None, "错误", "登录失败")


if __name__ == "__main__":
    import sys
    import pymysql
    app = QtWidgets.QApplication(sys.argv)
    db = pymysql.connect(
        host="localhost",
        user="root",
        password="10086",
        database="library",
        charset="utf8"
    )
    cursor = db.cursor()
    ui = Ui_Form(cursor)
    ui.show()
    sys.exit(app.exec())
