# Form implementation generated from reading ui file 'reserveForm.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(QtWidgets.QWidget):
    def __init__(self, bid, parent):
        super().__init__()
        self.cursor = parent.cursor
        self.bid = bid
        self.sid = parent.sid
        self.setupUi(self)
        self.parent = parent
        self.initReserveForm()

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.formLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 70, 351, 131))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(10, 10, 10, 10)
        self.formLayout.setSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.reserveSid = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.reserveSid.setObjectName("reserveSid")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.reserveSid)
        self.label_2 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.reserveBid = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.reserveBid.setObjectName("reserveBid")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.reserveBid)
        self.takeDate = QtWidgets.QDateEdit(parent=self.formLayoutWidget)
        self.takeDate.setObjectName("takeDate")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.takeDate)
        self.reserveSure = QtWidgets.QPushButton(parent=Form)
        self.reserveSure.setGeometry(QtCore.QRect(290, 230, 81, 31))
        self.reserveSure.setObjectName("reserveSure")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        # 设置预览书号不可编辑
        self.reserveBid.setReadOnly(True)
        self.reserveBid.setStyleSheet("background-color: #eee;")
        # 设置日期选择框只能选择当前日期之后的日期
        self.takeDate.setMinimumDate(QtCore.QDate.currentDate())
        # 设置默认日期为当前日期
        self.takeDate.setDate(QtCore.QDate.currentDate())
        # 确认预约按钮绑定事件
        self.reserveSure.clicked.connect(self.reserveBook)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "预约表单"))
        self.label.setText(_translate("Form", "学   号："))
        self.label_2.setText(_translate("Form", "取书日期："))
        self.label_3.setText(_translate("Form", "书   号："))
        self.reserveSure.setText(_translate("Form", "确认预约"))

    # 初始化预约表单
    def initReserveForm(self):
        self.reserveBid.setText(str(self.bid))
        if self.sid:
            self.reserveSid.setText(str(self.sid))
            self.reserveSid.setReadOnly(True)
            self.reserveSid.setStyleSheet("background-color: #eee;")

    # 预约图书
    def reserveBook(self):
        sid = self.reserveSid.text()
        take_date = self.takeDate.text()
        bid = self.reserveBid.text()
        if sid == "" or take_date == "":
            QtWidgets.QMessageBox.warning(self, "警告", "请填写完整信息")
            return
        # 调用存储过程
        try:
            self.cursor.callproc("reserveBook", (sid, bid, take_date))
            QtWidgets.QMessageBox.information(self, "提示", "预约成功")
            self.close()
            self.parent.searchBook()
        except Exception as e:
            QtWidgets.QMessageBox.warning(self, "警告", e.args[1])
            return
